run:
  timeout: 5m
  go: "1.24"

linters:
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - copyloopvar
    - gocheckcompilerdirectives
    - goconst
    - gocritic
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

linters-settings:
  dupl:
    threshold: 200
  goconst:
    min-len: 5
    min-occurrences: 4
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
  goimports:
    local-prefixes: github.com/openclawrocks/k8s-operator
  govet:
    enable:
      - shadow
  misspell:
    locale: US
  revive:
    rules:
      - name: unexported-return
        disabled: true

issues:
  exclude-rules:
    # Test files can have longer functions and duplication
    - path: _test\.go
      linters:
        - dupl
        - goconst
        - gosec
    # Generated files
    - path: zz_generated
      linters:
        - all
  max-issues-per-linter: 0
  max-same-issues: 0
